### ISSUE TITLE
Review of Sherlock

### ISSUE THREAD

**Issue by vsoch** [stanford-rc/resource-explorer#2]
Hey @kcgthb - when you have some time, would you be able to take a look at:

 1. The attributes I've defined for Sherlock, are they complete and correct?
 2. The overall list of questions - am I missing anything important?

Both of which are defined as "resources" and "questions" in [this file](https://github.com/stanford-rc/resource-explorer/blob/master/resource-explorer.js) that drives the resource explorer. Basically, if someone comes to the interface, we'd want them to be able to select features they are looking for, and wind up with Sherlock as an option (or not).

**Comment by vsoch** [comment]
Updated version -> https://stanford-rc.github.io/resource-explorer/ @kcgthb what about the suggestions above?

**Comment by kcgthb** [comment]
I think it's fine, we probably don't want to bury users under too many options either. :)

**Comment by vsoch** [comment]
okay, thanks @kcgthb!
